FROM golang:1.21.3-alpine
RUN apk --no-cache add ca-certificates

ARG AZURE_STORAGE_ACCOUNT_NAME 
ARG AZURE_STORAGE_ACCOUNT_KEY
ENV AZURE_STORAGE_ACCOUNT_NAME $AZURE_STORAGE_ACCOUNT_NAME
ENV AZURE_STORAGE_ACCOUNT_KEY $AZURE_STORAGE_ACCOUNT_KEY

RUN echo $AZURE_STORAGE_ACCOUNT_NAME

RUN apk add build-base

# Define the rest of your dockerfile here
WORKDIR /app

# Copy over master files
COPY bin/master /app/master

ENTRYPOINT [ "./master" ]
